name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:

    strategy:
      matrix:
        php: [ '8.0', '8.1', '8.2', '8.3', '8.4' ]

    runs-on: ubuntu-latest

    name: PHP ${{ matrix.php }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{matrix.php}}

    - name: Set up TeXLive
      uses: zauguin/install-texlive@v4
      with:
        packages: scheme-basic latexmk listings float etoolbox footmisc

    - name: Install
      run: composer install

    - name: Test
      run: |
        composer validate
        composer test
