name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        php: [ '7.4', '8.0', '8.1' ]

    runs-on: ${{ matrix.os }}

    name: PHP ${{ matrix.php }} on ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{matrix.php}}

    - name: Install
      run: |
        sudo apt-get install -y texlive-base
        composer install

    - name: Test
      run: composer test
